import { parsePhoneLengths } from './helperFunctions'

export type Country = {
  code: string
  label: string
  dialCode: number
  flagUrl: string
  phoneLengthMin?: number
  phoneLengthMax?: number
  phoneLengths?: number[]
  flagCode?: string
  country?: string
}

const initialCountriesData: Omit<Country, 'flagUrl'>[] = [
  { label: 'Afghanistan', code: 'af', dialCode: 93 },
  { label: 'Albania', code: 'al', dialCode: 355 },
  { label: 'Algeria', code: 'dz', dialCode: 213 },
  { label: 'American Samoa', code: 'as', dialCode: 1684 },
  { label: 'Andorra', code: 'ad', dialCode: 376 },
  { label: 'Angola', code: 'ao', dialCode: 244 },
  { label: 'Anguilla', code: 'ai', dialCode: 1264 },
  { label: 'Antigua and Barbuda', code: 'ag', dialCode: 1268 },
  { label: 'Argentina', code: 'ar', dialCode: 54 },
  { label: 'Armenia', code: 'am', dialCode: 374 },
  { label: 'Aruba', code: 'aw', dialCode: 297 },
  { label: 'Australia', code: 'au', dialCode: 61 },
  { label: 'Austria', code: 'at', dialCode: 43 },
  { label: 'Azerbaijan', code: 'az', dialCode: 994 },
  { label: 'Bahamas', code: 'bs', dialCode: 1242 },
  { label: 'Bahrain', code: 'bh', dialCode: 973 },
  { label: 'Bangladesh', code: 'bd', dialCode: 880 },
  { label: 'Barbados', code: 'bb', dialCode: 1246 },
  { label: 'Belarus', code: 'by', dialCode: 375 },
  { label: 'Belgium', code: 'be', dialCode: 32 },
  { label: 'Belize', code: 'bz', dialCode: 501 },
  { label: 'Benin', code: 'bj', dialCode: 229 },
  { label: 'Bermuda', code: 'bm', dialCode: 1441 },
  { label: 'Bhutan', code: 'bt', dialCode: 975 },
  { label: 'Bolivia', code: 'bo', dialCode: 591 },
  { label: 'Bosnia and Herzegovina', code: 'ba', dialCode: 387 },
  { label: 'Botswana', code: 'bw', dialCode: 267 },
  { label: 'Brazil', code: 'br', dialCode: 55 },
  { label: 'British Indian Ocean Territory', code: 'io', dialCode: 246 },
  { label: 'British Virgin Islands', code: 'vg', dialCode: 1284 },
  { label: 'Brunei', code: 'bn', dialCode: 673 },
  { label: 'Bulgaria', code: 'bg', dialCode: 359 },
  { label: 'Burkina Faso', code: 'bf', dialCode: 226 },
  { label: 'Burundi', code: 'bi', dialCode: 257 },
  { label: 'Cambodia', code: 'kh', dialCode: 855 },
  { label: 'Cameroon', code: 'cm', dialCode: 237 },
  { label: 'Canada', code: 'ca', dialCode: 1 },
  { label: 'Cape Verde', code: 'cv', dialCode: 238 },
  { label: 'Caribbean Netherlands', code: 'bq', dialCode: 599 },
  { label: 'Cayman Islands', code: 'ky', dialCode: 1345 },
  { label: 'Central African Republic', code: 'cf', dialCode: 236 },
  { label: 'Chad', code: 'td', dialCode: 235 },
  { label: 'Chile', code: 'cl', dialCode: 56 },
  { label: 'China', code: 'cn', dialCode: 86 },
  { label: 'Colombia', code: 'co', dialCode: 57 },
  { label: 'Comoros', code: 'km', dialCode: 269 },
  { label: 'Congo (DRC)', code: 'cd', dialCode: 243 },
  { label: 'Congo (Republic)', code: 'cg', dialCode: 242 },
  { label: 'Cook Islands', code: 'ck', dialCode: 682 },
  { label: 'Costa Rica', code: 'cr', dialCode: 506 },
  { label: 'Côte d’Ivoire', code: 'ci', dialCode: 225 },
  { label: 'Croatia', code: 'hr', dialCode: 385 },
  { label: 'Cuba', code: 'cu', dialCode: 53 },
  { label: 'Curaçao', code: 'cw', dialCode: 599 },
  { label: 'Cyprus', code: 'cy', dialCode: 357 },
  { label: 'Czech Republic', code: 'cz', dialCode: 420 },
  { label: 'Denmark', code: 'dk', dialCode: 45 },
  { label: 'Djibouti', code: 'dj', dialCode: 253 },
  { label: 'Dominica', code: 'dm', dialCode: 1767 },
  { label: 'Dominican Republic', code: 'do', dialCode: 1 },
  { label: 'Ecuador', code: 'ec', dialCode: 593 },
  { label: 'Egypt', code: 'eg', dialCode: 20 },
  { label: 'El Salvador', code: 'sv', dialCode: 503 },
  { label: 'Equatorial Guinea', code: 'gq', dialCode: 240 },
  { label: 'Eritrea', code: 'er', dialCode: 291 },
  { label: 'Estonia', code: 'ee', dialCode: 372 },
  { label: 'Ethiopia', code: 'et', dialCode: 251 },
  { label: 'Falkland Islands', code: 'fk', dialCode: 500 },
  { label: 'Faroe Islands', code: 'fo', dialCode: 298 },
  { label: 'Fiji', code: 'fj', dialCode: 679 },
  { label: 'Finland', code: 'fi', dialCode: 358 },
  { label: 'France', code: 'fr', dialCode: 33 },
  { label: 'French Guiana', code: 'gf', dialCode: 594 },
  { label: 'French Polynesia', code: 'pf', dialCode: 689 },
  { label: 'Gabon', code: 'ga', dialCode: 241 },
  { label: 'Gambia', code: 'gm', dialCode: 220 },
  { label: 'Georgia', code: 'ge', dialCode: 995 },
  { label: 'Germany', code: 'de', dialCode: 49 },
  { label: 'Ghana', code: 'gh', dialCode: 233 },
  { label: 'Gibraltar', code: 'gi', dialCode: 350 },
  { label: 'Greece', code: 'gr', dialCode: 30 },
  { label: 'Greenland', code: 'gl', dialCode: 299 },
  { label: 'Grenada', code: 'gd', dialCode: 1473 },
  { label: 'Guadeloupe', code: 'gp', dialCode: 590 },
  { label: 'Guam', code: 'gu', dialCode: 1671 },
  { label: 'Guatemala', code: 'gt', dialCode: 502 },
  { label: 'Guinea', code: 'gn', dialCode: 224 },
  { label: 'Guinea-Bissau', code: 'gw', dialCode: 245 },
  { label: 'Guyana', code: 'gy', dialCode: 592 },
  { label: 'Haiti', code: 'ht', dialCode: 509 },
  { label: 'Honduras', code: 'hn', dialCode: 504 },
  { label: 'Hong Kong', code: 'hk', dialCode: 852 },
  { label: 'Hungary', code: 'hu', dialCode: 36 },
  { label: 'Iceland', code: 'is', dialCode: 354 },
  { label: 'India', code: 'in', dialCode: 91 },
  { label: 'Indonesia', code: 'id', dialCode: 62 },
  { label: 'Iran', code: 'ir', dialCode: 98 },
  { label: 'Iraq', code: 'iq', dialCode: 964 },
  { label: 'Ireland', code: 'ie', dialCode: 353 },
  { label: 'Israel', code: 'il', dialCode: 972 },
  { label: 'Italy', code: 'it', dialCode: 39 },
  { label: 'Jamaica', code: 'jm', dialCode: 1876 },
  { label: 'Japan', code: 'jp', dialCode: 81 },
  { label: 'Jordan', code: 'jo', dialCode: 962 },
  { label: 'Kazakhstan', code: 'kz', dialCode: 7 },
  { label: 'Kenya', code: 'ke', dialCode: 254 },
  { label: 'Kiribati', code: 'ki', dialCode: 686 },
  { label: 'Kuwait', code: 'kw', dialCode: 965 },
  { label: 'Kyrgyzstan', code: 'kg', dialCode: 996 },
  { label: 'Laos', code: 'la', dialCode: 856 },
  { label: 'Latvia', code: 'lv', dialCode: 371 },
  { label: 'Lebanon', code: 'lb', dialCode: 961 },
  { label: 'Lesotho', code: 'ls', dialCode: 266 },
  { label: 'Liberia', code: 'lr', dialCode: 231 },
  { label: 'Libya', code: 'ly', dialCode: 218 },
  { label: 'Liechtenstein', code: 'li', dialCode: 423 },
  { label: 'Lithuania', code: 'lt', dialCode: 370 },
  { label: 'Luxembourg', code: 'lu', dialCode: 352 },
  { label: 'Macau', code: 'mo', dialCode: 853 },
  { label: 'Macedonia', code: 'mk', dialCode: 389 },
  { label: 'Madagascar', code: 'mg', dialCode: 261 },
  { label: 'Malawi', code: 'mw', dialCode: 265 },
  { label: 'Malaysia', code: 'my', dialCode: 60 },
  { label: 'Maldives', code: 'mv', dialCode: 960 },
  { label: 'Mali', code: 'ml', dialCode: 223 },
  { label: 'Malta', code: 'mt', dialCode: 356 },
  { label: 'Marshall Islands', code: 'mh', dialCode: 692 },
  { label: 'Martinique', code: 'mq', dialCode: 596 },
  { label: 'Mauritania', code: 'mr', dialCode: 222 },
  { label: 'Mauritius', code: 'mu', dialCode: 230 },
  { label: 'Mexico', code: 'mx', dialCode: 52 },
  { label: 'Micronesia', code: 'fm', dialCode: 691 },
  { label: 'Moldova', code: 'md', dialCode: 373 },
  { label: 'Monaco', code: 'mc', dialCode: 377 },
  { label: 'Mongolia', code: 'mn', dialCode: 976 },
  { label: 'Montenegro', code: 'me', dialCode: 382 },
  { label: 'Montserrat', code: 'ms', dialCode: 1664 },
  { label: 'Morocco', code: 'ma', dialCode: 212 },
  { label: 'Mozambique', code: 'mz', dialCode: 258 },
  { label: 'Myanmar', code: 'mm', dialCode: 95 },
  { label: 'Namibia', code: 'na', dialCode: 264 },
  { label: 'Nauru', code: 'nr', dialCode: 674 },
  { label: 'Nepal', code: 'np', dialCode: 977 },
  { label: 'Netherlands', code: 'nl', dialCode: 31 },
  { label: 'New Caledonia', code: 'nc', dialCode: 687 },
  { label: 'New Zealand', code: 'nz', dialCode: 64 },
  { label: 'Nicaragua', code: 'ni', dialCode: 505 },
  { label: 'Niger', code: 'ne', dialCode: 227 },
  { label: 'Nigeria', code: 'ng', dialCode: 234 },
  { label: 'Niue', code: 'nu', dialCode: 683 },
  { label: 'Norfolk Island', code: 'nf', dialCode: 672 },
  { label: 'North Korea', code: 'kp', dialCode: 850 },
  { label: 'Northern Mariana Islands', code: 'mp', dialCode: 1670 },
  { label: 'Norway', code: 'no', dialCode: 47 },
  { label: 'Oman', code: 'om', dialCode: 968 },
  { label: 'Pakistan', code: 'pk', dialCode: 92 },
  { label: 'Palau', code: 'pw', dialCode: 680 },
  { label: 'Palestine', code: 'ps', dialCode: 970 },
  { label: 'Panama', code: 'pa', dialCode: 507 },
  { label: 'Papua New Guinea', code: 'pg', dialCode: 675 },
  { label: 'Paraguay', code: 'py', dialCode: 595 },
  { label: 'Peru', code: 'pe', dialCode: 51 },
  { label: 'Philippines', code: 'ph', dialCode: 63 },
  { label: 'Poland', code: 'pl', dialCode: 48 },
  { label: 'Portugal', code: 'pt', dialCode: 351 },
  { label: 'Puerto Rico', code: 'pr', dialCode: 1 },
  { label: 'Qatar', code: 'qa', dialCode: 974 },
  { label: 'Réunion', code: 're', dialCode: 262 },
  { label: 'Romania', code: 'ro', dialCode: 40 },
  { label: 'Russia', code: 'ru', dialCode: 7 },
  { label: 'Rwanda', code: 'rw', dialCode: 250 },
  { label: 'Saint Barthélemy', code: 'bl', dialCode: 590 },
  { label: 'Saint Helena', code: 'sh', dialCode: 290 },
  { label: 'Saint Kitts and Nevis', code: 'kn', dialCode: 1869 },
  { label: 'Saint Lucia', code: 'lc', dialCode: 1758 },
  { label: 'Saint Martin', code: 'mf', dialCode: 590 },
  { label: 'Saint Pierre and Miquelon', code: 'pm', dialCode: 508 },
  { label: 'Saint Vincent and the Grenadines', code: 'vc', dialCode: 1784 },
  { label: 'Samoa', code: 'ws', dialCode: 685 },
  { label: 'San Marino', code: 'sm', dialCode: 378 },
  { label: 'São Tomé and Príncipe', code: 'st', dialCode: 239 },
  { label: 'Saudi Arabia', code: 'sa', dialCode: 966 },
  { label: 'Senegal', code: 'sn', dialCode: 221 },
  { label: 'Serbia', code: 'rs', dialCode: 381 },
  { label: 'Seychelles', code: 'sc', dialCode: 248 },
  { label: 'Sierra Leone', code: 'sl', dialCode: 232 },
  { label: 'Singapore', code: 'sg', dialCode: 65 },
  { label: 'Sint Maarten', code: 'sx', dialCode: 1721 },
  { label: 'Slovakia', code: 'sk', dialCode: 421 },
  { label: 'Slovenia', code: 'si', dialCode: 386 },
  { label: 'Solomon Islands', code: 'sb', dialCode: 677 },
  { label: 'Somalia', code: 'so', dialCode: 252 },
  { label: 'South Africa', code: 'za', dialCode: 27 },
  { label: 'South Korea', code: 'kr', dialCode: 82 },
  { label: 'South Sudan', code: 'ss', dialCode: 211 },
  { label: 'Spain', code: 'es', dialCode: 34 },
  { label: 'Sri Lanka', code: 'lk', dialCode: 94 },
  { label: 'Sudan', code: 'sd', dialCode: 249 },
  { label: 'Suriname', code: 'sr', dialCode: 597 },
  { label: 'Swaziland', code: 'sz', dialCode: 268 },
  { label: 'Sweden', code: 'se', dialCode: 46 },
  { label: 'Switzerland', code: 'ch', dialCode: 41 },
  { label: 'Syria', code: 'sy', dialCode: 963 },
  { label: 'Taiwan', code: 'tw', dialCode: 886 },
  { label: 'Tajikistan', code: 'tj', dialCode: 992 },
  { label: 'Tanzania', code: 'tz', dialCode: 255 },
  { label: 'Thailand', code: 'th', dialCode: 66 },
  { label: 'Timor-Leste', code: 'tl', dialCode: 670 },
  { label: 'Togo', code: 'tg', dialCode: 228 },
  { label: 'Tokelau', code: 'tk', dialCode: 690 },
  { label: 'Tonga', code: 'to', dialCode: 676 },
  { label: 'Trinidad and Tobago', code: 'tt', dialCode: 1868 },
  { label: 'Tunisia', code: 'tn', dialCode: 216 },
  { label: 'Turkey', code: 'tr', dialCode: 90 },
  { label: 'Turkmenistan', code: 'tm', dialCode: 993 },
  { label: 'Turks and Caicos Islands', code: 'tc', dialCode: 1649 },
  { label: 'Tuvalu', code: 'tv', dialCode: 688 },
  { label: 'U.S. Virgin Islands', code: 'vi', dialCode: 1340 },
  { label: 'Uganda', code: 'ug', dialCode: 256 },
  { label: 'Ukraine', code: 'ua', dialCode: 380 },
  { label: 'United Arab Emirates', code: 'ae', dialCode: 971 },
  { label: 'United Kingdom', code: 'gb', dialCode: 44 },
  { label: 'United States', code: 'us', dialCode: 1 },
  { label: 'Uruguay', code: 'uy', dialCode: 598 },
  { label: 'Uzbekistan', code: 'uz', dialCode: 998 },
  { label: 'Vanuatu', code: 'vu', dialCode: 678 },
  { label: 'Vatican City', code: 'va', dialCode: 39 },
  { label: 'Venezuela', code: 've', dialCode: 58 },
  { label: 'Vietnam', code: 'vn', dialCode: 84 },
  { label: 'Wallis and Futuna', code: 'wf', dialCode: 681 },
  { label: 'Yemen', code: 'ye', dialCode: 967 },
  { label: 'Zambia', code: 'zm', dialCode: 260 },
  { label: 'Zimbabwe', code: 'zw', dialCode: 263 },
]

// Fusion des données de longueur de téléphone avec countriesData
const phoneLengthsData = [
  {
    flagCode: 'KP',
    country: 'North Korea',
    phoneNumberLengthByCountry_phLengthMax: 17,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 17',
  },
  {
    flagCode: 'AU',
    country: 'Australia',
    phoneNumberLengthByCountry_phLengthMax: 15,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 15',
  },
  {
    flagCode: 'JP',
    country: 'Japan',
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 13',
  },
  {
    flagCode: 'DE',
    country: 'Germany',
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 13',
  },
  {
    flagCode: 'SE',
    country: 'Sweden',
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 13',
  },
  {
    flagCode: 'AT',
    country: 'Austria',
    phoneNumberLengthByCountry_phLengthMax: 13,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 13',
  },
  {
    flagCode: 'CN',
    country: 'China',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 12',
  },
  {
    flagCode: 'CZ',
    country: 'Czech Republic',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 12',
  },
  {
    flagCode: 'CH',
    country: 'Switzerland',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 12',
  },
  {
    flagCode: 'RS',
    country: 'Serbia',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 12',
  },
  {
    flagCode: 'SG',
    country: 'Singapore',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 12',
  },
  {
    flagCode: 'FI',
    country: 'Finland',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 12',
  },
  {
    flagCode: 'HR',
    country: 'Croatia',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 12',
  },
  {
    flagCode: 'ME',
    country: 'Montenegro',
    phoneNumberLengthByCountry_phLengthMax: 12,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 12',
  },
  {
    flagCode: 'PK',
    country: 'Pakistan',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 11',
  },
  {
    flagCode: 'IT',
    country: 'Italy',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: null,
    phoneNumberLengthByCountry_phLength: 'up to 11',
  },
  {
    flagCode: 'KR',
    country: 'South Korea',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 11',
  },
  {
    flagCode: 'PE',
    country: 'Peru',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 11',
  },
  {
    flagCode: 'PG',
    country: 'Papua New Guinea',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 11',
  },
  {
    flagCode: 'PT',
    country: 'Portugal',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: '9 or 11',
  },
  {
    flagCode: 'SV',
    country: 'El Salvador',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7, 8 or 11',
  },
  {
    flagCode: 'IE',
    country: 'Ireland',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 11',
  },
  {
    flagCode: 'UY',
    country: 'Uruguay',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 11',
  },
  {
    flagCode: 'CY',
    country: 'Cyprus',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 or 11',
  },
  {
    flagCode: 'LU',
    country: 'Luxembourg',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 11',
  },
  {
    flagCode: 'VA',
    country: 'Vatican City',
    phoneNumberLengthByCountry_phLengthMax: 11,
    phoneNumberLengthByCountry_phLengthMin: null,
    phoneNumberLengthByCountry_phLength: 'up to 11',
  },
  {
    flagCode: 'IN',
    country: 'India',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 10',
  },
  {
    flagCode: 'US',
    country: 'United States',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'ID',
    country: 'Indonesia',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 10',
  },
  {
    flagCode: 'NG',
    country: 'Nigeria',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 10',
  },
  {
    flagCode: 'BR',
    country: 'Brazil',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'BD',
    country: 'Bangladesh',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 10',
  },
  {
    flagCode: 'RU',
    country: 'Russia',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'MX',
    country: 'Mexico',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'PH',
    country: 'Philippines',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 10',
  },
  {
    flagCode: 'VN',
    country: 'Vietnam',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 10',
  },
  {
    flagCode: 'IR',
    country: 'Iran',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 10',
  },
  {
    flagCode: 'TR',
    country: 'Turkey',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'GB',
    country: 'United Kingdom',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 10',
  },
  {
    flagCode: 'KE',
    country: 'Kenya',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 10',
  },
  {
    flagCode: 'CO',
    country: 'Colombia',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 or 10',
  },
  {
    flagCode: 'IQ',
    country: 'Iraq',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 10',
  },
  {
    flagCode: 'AR',
    country: 'Argentina',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'CA',
    country: 'Canada',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'MG',
    country: 'Madagascar',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: '9 to 10',
  },
  {
    flagCode: 'VE',
    country: 'Venezuela',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'SY',
    country: 'Syria',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 10',
  },
  {
    flagCode: 'KZ',
    country: 'Kazakhstan',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'ZW',
    country: 'Zimbabwe',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 10',
  },
  {
    flagCode: 'DO',
    country: 'Dominican Republic',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(809/829) + 7',
  },
  {
    flagCode: 'GR',
    country: 'Greece',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: 10,
  },
  {
    flagCode: 'BY',
    country: 'Belarus',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: '9 to 10',
  },
  {
    flagCode: 'LA',
    country: 'Laos',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 10',
  },
  {
    flagCode: 'NZ',
    country: 'New Zealand',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: '3 to 10',
  },
  {
    flagCode: 'PR',
    country: 'Puerto Rico',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(787/939) + 7',
  },
  {
    flagCode: 'NA',
    country: 'Namibia',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 10',
  },
  {
    flagCode: 'JM',
    country: 'Jamaica',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(876) + 7',
  },
  {
    flagCode: 'TT',
    country: 'Trinidad and Tobago',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(868) + 7',
  },
  {
    flagCode: 'EE',
    country: 'Estonia',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 10',
  },
  {
    flagCode: 'BS',
    country: 'Bahamas',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(242) + 7',
  },
  {
    flagCode: 'BB',
    country: 'Barbados',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(246) + 7',
  },
  {
    flagCode: 'LC',
    country: 'Saint Lucia',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(758) + 7',
  },
  {
    flagCode: 'GU',
    country: 'Guam',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(671) + 7',
  },
  {
    flagCode: 'GD',
    country: 'Grenada',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(473) + 7',
  },
  {
    flagCode: 'VC',
    country: 'Saint Vincent and the Grenadines',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(784) + 7',
  },
  {
    flagCode: 'AG',
    country: 'Antigua and Barbuda',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(268) + 7',
  },
  {
    flagCode: 'VI',
    country: 'United States Virgin Islands',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(340) + 7',
  },
  {
    flagCode: 'KY',
    country: 'Cayman Islands',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(345) + 7',
  },
  {
    flagCode: 'DM',
    country: 'Dominica',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(767) + 7',
  },
  {
    flagCode: 'BM',
    country: 'Bermuda',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(441) + 7',
  },
  {
    flagCode: 'KN',
    country: 'Saint Kitts and Nevis',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(869) + 7',
  },
  {
    flagCode: 'TC',
    country: 'Turks and Caicos Islands',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(649) + 7',
  },
  {
    flagCode: 'AS',
    country: 'American Samoa',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(684) + 7',
  },
  {
    flagCode: 'SX',
    country: 'Sint Maarten',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(721) + 7',
  },
  {
    flagCode: 'VG',
    country: 'British Virgin Islands',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(284) + 7',
  },
  {
    flagCode: 'SM',
    country: 'San Marino',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 10',
  },
  {
    flagCode: 'AI',
    country: 'Anguilla',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(264) + 7',
  },
  {
    flagCode: 'MS',
    country: 'Montserrat',
    phoneNumberLengthByCountry_phLengthMax: 10,
    phoneNumberLengthByCountry_phLengthMin: 10,
    phoneNumberLengthByCountry_phLength: '(664) + 7',
  },
  {
    flagCode: 'ET',
    country: 'Ethiopia',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'EG',
    country: 'Egypt',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 9',
  },
  {
    flagCode: 'CD',
    country: 'DR Congo',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 9',
  },
  {
    flagCode: 'TH',
    country: 'Thailand',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 or 9',
  },
  {
    flagCode: 'TZ',
    country: 'Tanzania',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'FR',
    country: 'France',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'ZA',
    country: 'South Africa',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'MM',
    country: 'Myanmar',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 9',
  },
  {
    flagCode: 'SD',
    country: 'Sudan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'UG',
    country: 'Uganda',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'ES',
    country: 'Spain',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'DZ',
    country: 'Algeria',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 or 9',
  },
  {
    flagCode: 'AF',
    country: 'Afghanistan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'YE',
    country: 'Yemen',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 9',
  },
  {
    flagCode: 'AO',
    country: 'Angola',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'UA',
    country: 'Ukraine',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'MA',
    country: 'Morocco',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'PL',
    country: 'Poland',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 9',
  },
  {
    flagCode: 'UZ',
    country: 'Uzbekistan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'MY',
    country: 'Malaysia',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 9',
  },
  {
    flagCode: 'MZ',
    country: 'Mozambique',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'GH',
    country: 'Ghana',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 9',
  },
  {
    flagCode: 'SA',
    country: 'Saudi Arabia',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'NP',
    country: 'Nepal',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'LK',
    country: 'Sri Lanka',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'TW',
    country: 'Taiwan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'ZM',
    country: 'Zambia',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'CL',
    country: 'Chile',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'SN',
    country: 'Senegal',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'RO',
    country: 'Romania',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'NL',
    country: 'Netherlands',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'RW',
    country: 'Rwanda',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'BE',
    country: 'Belgium',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'JO',
    country: 'Jordan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 9',
  },
  {
    flagCode: 'AE',
    country: 'United Arab Emirates',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'TJ',
    country: 'Tajikistan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'AZ',
    country: 'Azerbaijan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'HU',
    country: 'Hungary',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'IL',
    country: 'Israel',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'LY',
    country: 'Libya',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: '8 to 9',
  },
  {
    flagCode: 'HK',
    country: 'Hong Kong',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4, 8 to 9',
  },
  {
    flagCode: 'KG',
    country: 'Kyrgyzstan',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'PY',
    country: 'Paraguay',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 9',
  },
  {
    flagCode: 'BG',
    country: 'Bulgaria',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 9',
  },
  {
    flagCode: 'SK',
    country: 'Slovakia',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 to 9',
  },
  {
    flagCode: 'GE',
    country: 'Georgia',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'AL',
    country: 'Albania',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: '3 to 9',
  },
  {
    flagCode: 'GQ',
    country: 'Equatorial Guinea',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'IS',
    country: 'Iceland',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 or 9',
  },
  {
    flagCode: 'GP',
    country: 'Guadeloupe',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'MQ',
    country: 'Martinique',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'GF',
    country: 'French Guiana',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 9,
    phoneNumberLengthByCountry_phLength: 9,
  },
  {
    flagCode: 'AD',
    country: 'Andorra',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6, 8 or 9',
  },
  {
    flagCode: 'LI',
    country: 'Liechtenstein',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 9',
  },
  {
    flagCode: 'MC',
    country: 'Monaco',
    phoneNumberLengthByCountry_phLengthMax: 9,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 9',
  },
  {
    flagCode: 'CI',
    country: 'Ivory Coast',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'CM',
    country: 'Cameroon',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'NE',
    country: 'Niger',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'ML',
    country: 'Mali',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'BF',
    country: 'Burkina Faso',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'MW',
    country: 'Malawi',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 or 8',
  },
  {
    flagCode: 'TD',
    country: 'Chad',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'SO',
    country: 'Somalia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 to 8',
  },
  {
    flagCode: 'GT',
    country: 'Guatemala',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'EC',
    country: 'Ecuador',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'KH',
    country: 'Cambodia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'GN',
    country: 'Guinea',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'BJ',
    country: 'Benin',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'BI',
    country: 'Burundi',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'BO',
    country: 'Bolivia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'TN',
    country: 'Tunisia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'HT',
    country: 'Haiti',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'HN',
    country: 'Honduras',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'CU',
    country: 'Cuba',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 8',
  },
  {
    flagCode: 'TG',
    country: 'Togo',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'SL',
    country: 'Sierra Leone',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'TM',
    country: 'Turkmenistan',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'NI',
    country: 'Nicaragua',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'DK',
    country: 'Denmark',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'LB',
    country: 'Lebanon',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'LR',
    country: 'Liberia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'NO',
    country: 'Norway',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 or 8',
  },
  {
    flagCode: 'CF',
    country: 'Central African Republic',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'OM',
    country: 'Oman',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'CR',
    country: 'Costa Rica',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'KW',
    country: 'Kuwait',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 or 8',
  },
  {
    flagCode: 'PA',
    country: 'Panama',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 or 8',
  },
  {
    flagCode: 'MN',
    country: 'Mongolia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'BA',
    country: 'Bosnia and Herzegovina',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'QA',
    country: 'Qatar',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: '3 to 8',
  },
  {
    flagCode: 'MD',
    country: 'Moldova',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'AM',
    country: 'Armenia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'LT',
    country: 'Lithuania',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'BW',
    country: 'Botswana',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'LS',
    country: 'Lesotho',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'SI',
    country: 'Slovenia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'LV',
    country: 'Latvia',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 or 8',
  },
  {
    flagCode: 'BH',
    country: 'Bahrain',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'SZ',
    country: 'Eswatini',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'BT',
    country: 'Bhutan',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'MO',
    country: 'Macau',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'MT',
    country: 'Malta',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'CW',
    country: 'Curacao',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: '7 to 8',
  },
  {
    flagCode: 'GI',
    country: 'Gibraltar',
    phoneNumberLengthByCountry_phLengthMax: 8,
    phoneNumberLengthByCountry_phLengthMin: 8,
    phoneNumberLengthByCountry_phLength: 8,
  },
  {
    flagCode: 'MR',
    country: 'Mauritania',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'ER',
    country: 'Eritrea',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'GM',
    country: 'Gambia',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'GA',
    country: 'Gabon',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 or 7',
  },
  {
    flagCode: 'MU',
    country: 'Mauritius',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'FJ',
    country: 'Fiji',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'KM',
    country: 'Comoros',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'GY',
    country: 'Guyana',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'SR',
    country: 'Suriname',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: '6 to 7',
  },
  {
    flagCode: 'MV',
    country: 'Maldives',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'CV',
    country: 'Cape Verde',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'BN',
    country: 'Brunei',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'BZ',
    country: 'Belize',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'VU',
    country: 'Vanuatu',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 or 7',
  },
  {
    flagCode: 'ST',
    country: 'Sao Tome and Principe',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'WS',
    country: 'Samoa',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 3,
    phoneNumberLengthByCountry_phLength: '3 to 7',
  },
  {
    flagCode: 'SC',
    country: 'Seychelles',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'FM',
    country: 'Micronesia',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'AW',
    country: 'Aruba',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'TO',
    country: 'Tonga',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 or 7',
  },
  {
    flagCode: 'MH',
    country: 'Marshall Islands',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'PW',
    country: 'Palau',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 7,
    phoneNumberLengthByCountry_phLength: 7,
  },
  {
    flagCode: 'NR',
    country: 'Nauru',
    phoneNumberLengthByCountry_phLengthMax: 7,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: '4 or 7',
  },
  {
    flagCode: 'DJ',
    country: 'Djibouti',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
  },
  {
    flagCode: 'NC',
    country: 'New Caledonia',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
  },
  {
    flagCode: 'PF',
    country: 'French Polynesia',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
  },
  {
    flagCode: 'FO',
    country: 'Faroe Islands',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
  },
  {
    flagCode: 'GL',
    country: 'Greenland',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
  },
  {
    flagCode: 'WF',
    country: 'Wallis and Futuna',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
  },
  {
    flagCode: 'TV',
    country: 'Tuvalu',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: '5 or 6',
  },
  {
    flagCode: 'PM',
    country: 'Saint Pierre and Miquelon',
    phoneNumberLengthByCountry_phLengthMax: 6,
    phoneNumberLengthByCountry_phLengthMin: 6,
    phoneNumberLengthByCountry_phLength: 6,
  },
  {
    flagCode: 'SB',
    country: 'Solomon Islands',
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
  },
  {
    flagCode: 'KI',
    country: 'Kiribati',
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
  },
  {
    flagCode: 'CK',
    country: 'Cook Islands',
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
  },
  {
    flagCode: 'FK',
    country: 'Falkland Islands',
    phoneNumberLengthByCountry_phLengthMax: 5,
    phoneNumberLengthByCountry_phLengthMin: 5,
    phoneNumberLengthByCountry_phLength: 5,
  },
  {
    flagCode: 'TK',
    country: 'Tokelau',
    phoneNumberLengthByCountry_phLengthMax: 4,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: 4,
  },
  {
    flagCode: 'NU',
    country: 'Niue',
    phoneNumberLengthByCountry_phLengthMax: 4,
    phoneNumberLengthByCountry_phLengthMin: 4,
    phoneNumberLengthByCountry_phLength: 4,
  },
]

// --- Fusion finale ---
export const countries: Country[] = initialCountriesData.map((country) => {
  const phoneData = phoneLengthsData.find(
    (p) =>
      p.flagCode?.toLowerCase() === country.code.toUpperCase() ||
      p.country?.toLowerCase() === country.label.toLowerCase(),
  )

  const parsed = phoneData ? parsePhoneLengths(phoneData) : {}

  return {
    ...country,
    flagUrl: `https://flagcdn.com/${country.code.toLowerCase()}.svg`,
    phoneLengthMin: parsed.min,
    phoneLengthMax: parsed.max,
    phoneLengths: parsed.lengths,
  }
})

/** Aliases for country lookup (e.g. API sends "USA" or "UK") */
const COUNTRY_ALIASES: Record<string, string> = {
  usa: 'us',
  uae: 'ae',
  uk: 'gb',
}

/**
 * Find country by code or label (case-insensitive). Use for display in customers, promotions, etc.
 */
export function getCountryByLabelOrCode(value: string): Country | null {
  if (!value?.trim()) return null
  const n = value.trim().toLowerCase()
  const byAlias = COUNTRY_ALIASES[n]
  if (byAlias) {
    const c = countries.find((x) => x.code.toLowerCase() === byAlias)
    if (c) return c
  }
  return countries.find((c) => c.code.toLowerCase() === n || c.label.toLowerCase() === n) ?? null
}

/**
 * Get display label and flag URL for a raw country value (e.g. from API).
 */
export function getCountryDisplay(value: string): {
  name: string
  flagUrl: string | null
} {
  const country = getCountryByLabelOrCode(value)
  if (country) return { name: country.label, flagUrl: country.flagUrl }
  return { name: value || 'Missing', flagUrl: null }
}
